### ISSUE TITLE
modernc.org/cc tweaks: non-standard parenthesized compound statement as expression not enabled

### ISSUE THREAD

**Issue by epsleq0** [xlab/c-for-go#110]
Creating bindings for a private project generates the following error message:

```
$ c-for-go lib.yml
  processing lib.yml ⠦[ERR] lib/core.h:471:1: non-standard parenthesized compound statement as expression not enabled (and 2 more errors)
```

`modernc.org/cc` has a suitable option (aka tweak), i.e. `EnableParenthesizedCompoundStatemen()`, unfortunately `c-for-go` does not use it: https://github.com/xlab/c-for-go/blob/master/parser/parser.go#L101

This leads to the following questions:
1. Is there a good reason for not enabling this specific tweak?
2. If not, should `c-for-go` set this option by default? Or should we make the list of tweaks configurable?

**Comment by xlab** [comment]
@epsleq0 I just didn't know it exists. It's ok to enable it, could you please send a PR?

Btw, in the version of CC used to create this I've tried to enable as many tweaks as possible to be all-inclusive. However, I could miss a few that were added later, also I didn't have time to refactor it all to use the latest version of CC. Its API has some changes.

Could you please enable that tweak in the version used by c-for-go? If it isn't there, then you'll have to wait until I rewrite that one day to use the modernst of all modern CCs.
