### ISSUE TITLE
c-for-go generating invalid go functions

### ISSUE THREAD

**Issue by nergdron** [xlab/c-for-go#117]
I'll preface this by saying I'm very new to `c-for-go` and how it operates. I'm looking at updating some library bindings that currently work with an old release of the library, but when I point it at the updated headers for the library, I get errors like this:

```
  processing vulkan.yml ⠏[WARN] cannot gofmt ../vulkan/cgo_helpers.go: ../vulkan/cgo_helpers.go:42347:17: expected '(', found '.' (and 10 more errors)
```

looking at `cgo_helpers.go`, it looks like `c-for-go` has generated some invalid function declarations with periods in them, which neither `go build` or `gofmt` is very happy with:

```
func copyPUnsafe.PointerBytes(slice *sliceHeader) (*unsafe.Pointer, *cgoAllocMap)
func allocUnsafe.PointerMemory(n int) unsafe.Pointer
```

is there something extra I'm missing that I need to do so it generates these functions differently? what's going on here? :sweat_smile:

**Comment by xlab** [comment]
Hey @nergdron which OS you're running? Also, Go version.

**Comment by nergdron** [comment]
hi @xlab, this is on Endeavour (an Arch variant) and go1.17.7.

**Comment by AllenDang** [comment]
Same issue here. Any progress on this?

**Comment by nergdron** [comment]
just a little update to this, it was occurring using the nvidia supplied vulkan headers. using the mesa headers with go v1.18.1, this doesn't occur. so you should be able to replicate using the `go-for-vulkan` repo and the nvidia vulkan headers.

**Comment by lotodore** [comment]
I've proposed a pull request to fix this, hopefully this does not cause side effects...
@AllenDang cimgui code generation works with this patch, so you might give it another try :-)

**Comment by AllenDang** [comment]
@lotodore Great! Let me have a try. Feedback to you later.

**Comment by AllenDang** [comment]
@lotodore A quick feedback, the problem is solved, but I still cannot generate working wrapper for cimgui. Do you have a working *.yml file which could compile?

**Comment by lotodore** [comment]
@AllenDang I've sent you an email to the address on your giu github page, so that we do not spam the other participants...
