### ISSUE TITLE
Can't use c-for-go

### ISSUE THREAD

**Issue by David00154** [xlab/c-for-go#119]
I wanted to create go bindings for hermes javascript engine with c-for-go but i'm confused. I don't know which of the header files to use from the github repository.

Here is the repository

https://github.com/facebook/hermes/tree/main/API/hermes

**Comment by xlab** [comment]
Hi David, so the lib you've pointed out is a C++ library and they have only C++ headers. That means it has no ABI compatibility and will not link with C and Go projects. Usually for C++ related progs, a C interface should be created, that uses extern "C" to export symbols https://stackoverflow.com/questions/1041866/what-is-the-effect-of-extern-c-in-c
