### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by SamuelMarks** [xlab/c-for-go#147]
Related: #15 #97

**Comment by salihdhaifullah** [comment]
c.for-go.com is down

**Comment by xlab** [comment]
Ok it's finally back. Thanks for poking me :)

**Comment by SamuelMarks** [comment]
Great to see. Yeah I've got like a dozen websites all on GitHub Actions/Pages. Its handy.

**Comment by SamuelMarks** [comment]
Great to see. Yeah I've got like a dozen websites all on GitHub Actions/Pages. It's handy.
