### ISSUE TITLE
https://for-go.com/ returns a 404

### ISSUE THREAD

**Issue by dh1tw** [xlab/c-for-go#16]
Hi, 

the page you have linked to returns a 404.

Tobias

**Comment by xlab** [comment]
Thanks for the report, the main issue to keep track in this
https://github.com/xlab/c-for-go/issues/15

I'm moving stuff around. As you can see, the project has been recently renamed too.

**Comment by dh1tw** [comment]
Any particular reason why you are renaming the project?

**Comment by xlab** [comment]
@dh1tw 

1) cgogen is hard to pronounce correctly
2) nobody can remember this name
3) cgogen is clear only when you know what's [cgo](https://blog.golang.org/c-go-cgo)
4) cgo + generator = cgogen was a brilliant idea, but in practice this name sucks

5) I'm going to add other languages as well, `java-for-go` for example. I want them to have the same suffix, so I won't end up explaining how cgogen relates to JNI. And I definitely don't want to name next project jnigen xD

**Comment by xlab** [comment]
The first version of the site is still up though https://cgogen.com
