### ISSUE TITLE
Go Bindings for Hamlib — feasible? 

### ISSUE THREAD

**Issue by dh1tw** [xlab/c-for-go#18]
Hi again,

I've made the first steps with c-for-go and I have understood the documentation.

However I would like to ask for your opinion if a proper Go binding is actually feasible for a medium to highly complex c library. In particular I would like to create a binding for [Hamlib](https://github.com/n0nb/hamlib). Thats a library which provides a unified interface to control plenty of different Radios through a unified interface. The main library is [rig.h](https://github.com/N0NB/hamlib/blob/master/include/hamlib/rig.h). The library contains plenty of Macros and some weird data structures, like nested structs or unions nested in structs.

I already started last year to write a manual binding, but if I could create one with c-for-go that would be actually much much better.

I wrote a SWIG binding, but it actually sucks. It's too close to C-Style and unfriendly to use (parameters have for example weird long names).

I would appreciate an honest opinion if a proper go-style binding is actually feasible.

Thanks!

**Comment by xlab** [comment]
@dh1tw 
Thanks, I wish more people were considering using c-for-go rather than manual labor!

The interface `hamlib/rig.h` looks like easy peasy, since I have a trained hand already, I quickly did a starter repo for you, feel free to clone and make all the required adjustments:

https://github.com/xlab/hamlib-go

It compiles and links fine under OS X (`brew install hamlib` beforehand), the header is not ideal, but feasible! You need to ensure that args are pointers where expected pointers and arrays where arrays are expected. Also you may add some getters/setters for raw structs. I left most structs raw because of too much inner state. A raw struct looks like this:

```
// RigCaps as declared in hamlib/rig.h:1135
type RigCaps C.struct_rig_caps
```

Later I can automate getter/setter generation, but for now it's one manual thing to do.

Good luck.

**Comment by xlab** [comment]
@dh1tw 
Also, you may prefer ALL_CAPS constants for easy migration of C code. Just sayin

**Comment by dh1tw** [comment]
Cool! Thanks for your work! Awesome! I just checked it and wrote a tiny test program. With the execption of some small strings which are not exported correctly (hamlib_version / hamlib_copyright), the test of the binding actually works! Pretty cool!

I started writing now the PtrTips.

However I have one question - I would like to make the binding more go-style. Almost all functions take as the first argument a pointer to an instance of a rig (radio). For example: 


```C
extern HAMLIB_EXPORT(int) rig_get_freq HAMLIB_PARAMS((RIG *rig, vfo_t vfo, freq_t *freq));
```

translates into: 

```go
// RigGetFreq function as declared in hamlib/rig.h:1545
func RigGetFreq(rig *Rig, vfo int32, freq *float64) int32 {
	crig, _ := (*C.RIG)(unsafe.Pointer(rig)), cgoAllocsUnknown
	cvfo, _ := (C.vfo_t)(vfo), cgoAllocsUnknown
	cfreq, _ := (*C.freq_t)(unsafe.Pointer(freq)), cgoAllocsUnknown
	__ret := C.rig_get_freq(crig, cvfo, cfreq)
	__v := (int32)(__ret)
	return __v
}
```

However I would prefer a more go-style function signature:

```go
func (rig *RIG) GetFreq(vfo int32) (float64, error) {
....
}
```

Would that be possible?

**Comment by xlab** [comment]
@dh1tw 

This would be dream if we can do this automatically, but actually we can't.
There is a lot of pitfalls, for example, this transform introduces a state, and there is no way to guess that state. And describing the state in YAML tips is harder than just write code.

I usually do high-level wrappers for this stuff, for example:

**generated:** https://github.com/xlab/pocketsphinx-go/tree/master/pocketsphinx
**wrapper:** https://github.com/xlab/pocketsphinx-go/tree/master/sphinx

**generated:** https://github.com/zenhotels/lmdb-go/tree/master/mdb
**wrapper:** https://github.com/zenhotels/lmdb-go/tree/master/lmdb

As you may notice, some wrappers are just to have OOP semantics, other wrappers manage the state,
internal resources, mutexes and other stuff, introducing a handy API.

The point of C bindings generation is to avoid handmade CGO calls, but making the API itself more idiomatic and handy will require some hands and soul of a human :)

**Comment by dh1tw** [comment]
ok, got it. I guess I asked for to much :-) In my particular case this means that I have to write actually again quite a log of code in order to wrap the entire hamlib-go API (as most of the functions are *rig related. If I understand it right I also have to wrap again all the CONSTs in order provide a unique interface to work with, right?

**Comment by xlab** [comment]
> I also have to wrap again all the CONSTs in order provide a unique interface to work with, right?
That was my preference, you don't have to. And you just can copy that file over..

> that I have to write actually again quite a log of code in order to wrap the entire hamlib-go API
Not much actually, but again, it's your preference to do so.

**Comment by xlab** [comment]
> In my particular case this means that I have to write actually again quite a lot of code

@dh1tw kinda ironic how you decided to write the whole binding by hand :)
Were there any problems with automated process?

**Comment by dh1tw** [comment]
Hey Maxim,
thanks for catching up! Well, before I got to know c-for-go I already had written most of the binding by hand. There is still some stuff missing, but I had at least something to work with. It's still on my task list to complete the binding.
I don't really recall why I didn't pursue using c-to-go further. I think the main reason was that I was in a hurry at that time to get at least parts of the binding up and working. 
I still prefer much more a binding which is at least in parts auto generated and before completing the hamlib binding by hand I will take again the time to thoroughly try to do it with c-to-go.
