### ISSUE TITLE
Documentation and project links to https://for-go.com broken

### ISSUE THREAD

**Issue by pwaller** [xlab/c-for-go#28]
The front page links to https://for-go.com, whose DNS does not currently resolve.

https://web-beta.archive.org/web/*/https://for-go.com seems to indicate it never existed?

https://cgogen.com/ still works.

**Comment by xlab** [comment]
Related to #15

**Comment by pwaller** [comment]
Sorry, missed the duplicate. (oops!)

It's unfortunate to change the documentation before the domain even exists. A colleague just took a look at this project after I mentioned it and expressed confusion that the links didn't work. It make the project seem immature.
