### ISSUE TITLE
 for-go.com: NXDOMAIN

### ISSUE THREAD

**Issue by cznic** [xlab/c-for-go#29]
@xlab 

Hi Max,

it seems the old domain (cgogen.go) still works and the while the new one does not yet. What about updating the `README` back to pointing to the working domain and then update it again when the new domain is ready?

**Comment by xlab** [comment]
It points both. The only way to resolve this is to remove the old domain so it won't confuse anyone anymore. Sorry for rough transition, shortage of time in the middle of the process.

**Comment by cznic** [comment]
> It points both.

But why it points to a NXDOMAIN in the first place? What is a broken link good for?

> The only way to resolve this is to remove the old domain so it won't confuse anyone anymore. 

Removing the working domain and pointing only to the non working one? That would confuse *everyone*. I don't get the idea, please explain ;-)

(Not trying to argue, I just obviously don't understand something)

**Comment by xlab** [comment]
I'm trying to migrate from cgogen naming to the new one.
The previous site is beautiful but not informative in any way, I don't see any bonus from having it alive.
But having it alive actually adds confusion, as cgogen is no longer the name of the project.

I was going to make this renaming as abruptly as possible, but stuck in the middle of the process.

Let me just leave it as it is right now, I'll get back later.

**Comment by xlab** [comment]
https://c.for-go.com
