### ISSUE TITLE
Cant find std libraries

### ISSUE THREAD

**Issue by askairon** [xlab/c-for-go#35]
I am getting errors like below for std libraries-
include file not found: vector

I tried using the ccincl flag and then I started getting an additional error-

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/include/stdint.h:31:43: unexpected '<', expected optional argument expression list or one of [&&, '!', '&', '(', ')', '*', '+', '-', '~', ++, --, _Alignof, character constant, floating-point constant, identifier, integer constant, long character constant, long string constant, sizeof, string literal]

**Comment by xlab** [comment]
Hi, can you provide more context please? Maybe the `.h` source part with your includes.

```cpp
 #include <vector>
```

It looks like C++ include, note that c-for-go currently works with C source files only.

Also, try running c-for-go with flags:

```
c-for-go -ccincl
c-for-go -ccdefs
```

**Comment by xlab** [comment]
@askairon if fixed please share a solution because I offered multiple options,
It's good to have the right one written... Thanks

**Comment by askairon** [comment]
I need to include some c++ headers, since you dont support it, I closed the issue
