### ISSUE TITLE
cgo: error: field has incomplete type

### ISSUE THREAD

**Issue by 1l0** [xlab/c-for-go#42]
I'm testing the bindings for Godot game engine on a repo(https://github.com/1l0/godot). `c-for-go` works for generating codes but that won't compile / go get / go install.
Steps to reproduce:
```
$ go get github.com/1l0/godot
# github.com/1l0/godot
_cgo_export.c:21:16: error: field has incomplete type 'godot_object' (aka 'void')
```
I don't get what is going on internally. Is [`typedef void godot_object;`](https://github.com/1l0/godot/blob/master/godot_headers/gdnative/gdnative.h#L136) a problem? Sorry if it's a wrong place to post this issue.

**Comment by xlab** [comment]
This is the correct place to post that :) After a bit of fiddling I was able to trace it back to the logic of function callback wrappers in c-for-go.

**Comment by 1l0** [comment]
Thanks! https://github.com/xlab/c-for-go/commit/66299e982daf7aa955a287097f2c3d3f6021f2a0 removes previous error but I get another error:
```
$ make 
c-for-go -out .. godot.yml
  processing godot.yml done.
$ make test
go build
# github.com/1l0/godot
./types.go:236: undefined: Uint8T
./types.go:335: undefined: Uint8T
./types.go:356: undefined: Uint8T
./types.go:592: undefined: Uint64T
./types.go:593: undefined: Int64T
./types.go:630: undefined: WcharT
./types.go:631: undefined: WcharT
./types.go:632: undefined: WcharT
./types.go:692: undefined: Int64T
./types.go:694: undefined: Int64T
./types.go:694: too many errors
make: *** [test] Error 2
```

**Comment by xlab** [comment]
@1l0 these errors are normal. You didn't include `uint8_t` type in your manifest, as well as the others. 

Unrelated, but still: I think c-for-go won't work with such crazy API as this struct with 700+ function pointers. :/

**Comment by xlab** [comment]
Oh wait, you can actually autogenerate a proper .h with .c bridge for calling using their `gdnative_api.json` instead of one big struct.

**Comment by xlab** [comment]
WAIT!!11 Why bother with `gdnative_api_struct.gen.h` when you can simply bind `gdnative/gdnative.h` ?! It seems correct and very simple.

**Comment by 1l0** [comment]
It seems like I didn't understand that how to use the tools properly. Thanks for your advice. Making bridge or using `gdnative/gdnative.h` directly either way I'll dig into it.
