### ISSUE TITLE
How to represent []float32 as *float32 ??

### ISSUE THREAD

**Issue by darmie** [xlab/c-for-go#53]
I am using the gles2 library that was generated by `c-for-go`

But I don't know what to do in this case:

```go
var view [2]float32
view[0] = 1
view[1] = 2
gl.Uniform2fv(c.shader.locations[glnvgLocVIEWSIZE], int32(len(view)), view[:])
```
`gl.Uinform2fv` is  type `func(location int32, count int32, value *float32)`

How do I convert [2]float32 to *float32 ??

**Comment by xlab** [comment]
`&view[0]`
