### ISSUE TITLE
"Creating a project" in wiki is unknown domain

### ISSUE THREAD

**Issue by utdrmac** [xlab/c-for-go#64]
"Creating a project" in wiki is unknown domain

**Comment by xlab** [comment]
I'll fix it soon. A minimal example could be found here 
https://github.com/xlab/vorbis-go

**Comment by dmjones** [comment]
Any progress on this? Can you post the contents into the Github wiki in the meantime?

**Comment by xlab** [comment]
@dmjones thanks for rising this up. Fixed
https://c.for-go.com
