### ISSUE TITLE
TypeTip return type uint32 -> error

### ISSUE THREAD

**Issue by Asalle** [xlab/c-for-go#75]
I'm working with [roc](https://github.com/roc-project/roc) and they use uint32 as the return error (0 - good, 1 - bad), can I somehow convert all `uint32` returns to `error`? 

Example:

`ROC_API int roc_sender_write(roc_sender* sender, const roc_frame* frame);`

Go code:

`SenderWrite(sender *Sender, frame *Frame) error`

**Comment by xlab** [comment]
Nope, not automatically, but you can create helpers for converting the result into error. Many C libs provide also functions that convert their int32 error codes into text, so combining them into helper is a good idea.

**Comment by xlab** [comment]
> I wrote a simple converter in roc-wrappers.go, also I opened an issue in c-for-go to find out if we can generate such things in the future.

Oh I see you've already done that step! Well, the error handling is more tricky than mapping 1/0 to success/fail, there is so much variations on that, so I avoided that feature in my generator. Sorry :)

**Comment by xlab** [comment]
> they use uint32 as the return error (0 - good, 1 - bad)

Actually, they use other notation too:

<img width="585" alt="Screenshot 2019-10-14 at 15 49 07" src="https://user-images.githubusercontent.com/477998/66752519-49150780-ee9a-11e9-9693-0ae900658231.png">

**Comment by Asalle** [comment]
Ah, that is true, I thought I messed up something! Thank you, I will move forward with the hand-written converter then! 🙂
