### ISSUE TITLE
Website down for extended period of time

### ISSUE THREAD

**Issue by MicahParks** [xlab/c-for-go#97]
It seems this project's website has been down for quite some time: https://c.for-go.com/

Is the website being worked on/broken?

![Screenshot_2020-08-27 c for-go com 522 Connection timed out(1)](https://user-images.githubusercontent.com/66095735/91454852-eee22280-e870-11ea-91b1-8b91d060a964.png)

**Comment by Matheus-Garbelini** [comment]
It's also down for me
